ci:
  collect:
    psiStrategy: desktop
    settings:
      preset: desktop
      onlyCategories: ["performance", "seo", "accessibility", "best-practices"]
      # skipping is-crawlable since vercel will prevent indexing on non prod urls
      skipAudits: ["is-crawlable"]
  assert:
    assertions:
      categories:performance:
        - warn
        - minScore: 1
      categories:seo:
        - error
        - minScore: 1
      categories:accessibility:
        - error
        - minScore: 1
      categories:best-practices:
        - error
        - minScore: 1
