rules:
  body-leading-blank: [1, always]
  body-max-line-length: [2, always, 100]
  footer-leading-blank: [1, always]
  footer-max-line-length: [2, always, 100]
  header-max-length: [2, always, 75]
  header-min-length: [2, always, 5]
  subject-case: [2, never, [sentence-case, start-case, pascal-case, upper-case]]
  subject-empty: [2, never]
  subject-full-stop: [2, never, '.']
  type-case: [2, always, lower-case]
  type-empty: [2, never]
  type-enum: [2, always, [test, feat, fix, chore, docs, refactor, style, ci]]
  scope-empty: [2, always]
  scope-case: [2, always, lower-case]
