extends:
  [
    'jimmy-guzman',
    'jimmy-guzman/typescript',
    'jimmy-guzman/react',
    'jimmy-guzman/jest',
    'jimmy-guzman/testing-library',
    'plugin:@next/next/recommended',
  ]
parserOptions:
  project: ['./tsconfig.json', './cypress/tsconfig.json']
rules:
  'dot-notation': off
  '@typescript-eslint/naming-convention': off
