export const pages = {
  home: {
    title: "jimmy.codes",
    heading: "Hi, I'm Jimmy",
    description:
      "Lead Engineer specializing in high-performance, scalable systems and developer experience. Passionate about mentorship, technical strategy, and modern software architecture.",
    keywords: [
      "jimmy guzman",
      "lead engineer",
      "software engineer",
      "typescript",
      "react",
      "nextjs",
      "astro",
      "scalable systems",
      "developer experience",
      "engineering leadership",
      "mentorship",
      "technical strategy",
      "frontend",
      "backend",
      "distributed systems",
      "platform engineering",
      "nx monorepo",
      "turborepo",
      "target",
      "ameriprise",
    ],
  },
  about: {
    title: "jimmy.codes | About Me",
    heading: "About Me",
    description:
      "Lead Engineer with 9+ years experience in high-performance systems, scalable architecture, and developer experience. Engineering leader passionate about mentorship and technical strategy.",
    keywords: [
      "jimmy guzman",
      "lead engineer",
      "target",
      "ameriprise",
      "engineering leadership",
      "scalable systems",
      "developer experience",
      "mentorship",
      "technical strategy",
    ],
  },
  blog: {
    title: "jimmy.codes | Blog",
    heading: "Blog",
    description:
      "Articles on the craft of building software, architecture, system design, code, and developer experience.",
    keywords: [
      "jimmy guzman blog",
      "technical articles",
      "scalable systems",
      "developer experience",
      "engineering leadership",
      "typescript",
      "react",
      "nextjs",
      "astro",
      "web development",
      "software architecture",
      "mentorship",
    ],
  },
  notes: {
    title: "jimmy.codes | Notes",
    heading: "Notes",
    description:
      "Notes on the craft of building software, architecture, system design, code, and developer experience.",
    keywords: [
      "jimmy guzman notes",
      "technical notes",
      "software architecture",
      "developer experience",
      "web development",
      "mentorship",
    ],
  },
  rss: {
    title: "jimmy.codes | RSS",
    description:
      "Articles and notes on the craft of building software, architecture, system design, code, and developer experience.",
  },
  notFound: {
    title: "jimmy.codes | 404",
    heading: "404",
  },
};
