name: Setup
description: Install everything for the repo

runs:
  using: composite
  steps:
    - name: 🏗 Setup bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: package.json

    - name: 🏗 Setup bun cache
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.bun }}-bun-

    - name: 📦 Install deps
      run: bun install
      shell: bash
